# Generated by Django 3.2.4 on 2021-06-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('number_of_pages', models.PositiveSmallIntegerField(default=0, verbose_name='Number Of Pages')),
                ('year_of_publication', models.DateField(verbose_name='Year of publication')),
                ('author', models.ManyToManyField(related_name='book_author', to='Content.Author', verbose_name='Author')),
                ('publisher', models.ManyToManyField(related_name='book_publisher', to='Content.Author', verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
